// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAan6W2-cm1FTlek-Lmf0PGry3OkB7_RbU',
    appId: '1:401280729427:android:54eddd49d5b2b72d9aa1a6',
    messagingSenderId: '401280729427',
    projectId: 'flutterfirebasedemo-c5947',
    storageBucket: 'flutterfirebasedemo-c5947.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8ruMp4pvKNeabEPqdniA4u9AL2Lpg5fo',
    appId: '1:401280729427:ios:52aa6b7fe4c5fc2a9aa1a6',
    messagingSenderId: '401280729427',
    projectId: 'flutterfirebasedemo-c5947',
    storageBucket: 'flutterfirebasedemo-c5947.appspot.com',
    androidClientId: '401280729427-d1usug8a3nkqlovomc0belvtqpdqj52g.apps.googleusercontent.com',
    iosClientId: '401280729427-0h54s72o0m7gn5j82r8ma52nckupq2ji.apps.googleusercontent.com',
    iosBundleId: 'com.myApp.eventsApp',
  );
}
